# NOTE: integration tests and more complex setup is prepared but not enabled:
# _cider-ci_include: cider-ci/jobs.yml

# for now, basic unit test config:
jobs:
  'Tests':

    run-on: [{type: branch, include-match: ^.*$}]

    context:

      task-defaults:
        max-auto-trials: 1
        traits:
          nodejs: true
        git-options: {submodules: {clone: true, timeout: 120}}

      tasks:

        build:
          scripts:
            build:
              name: 'Build'
              body: npm run -s ci:build | cat > buildlog.json && tar -czf build.tgz build/*
            filesize:
              name: 'Is the app filesize less than 1MB? (gzipped)'
              start-when: [script: build]
              body: |
                #!/usr/bin/env node
                var size = require("fs").statSync("./build.tgz").size
                console.log((size/1024).toFixed(2)+"K")
                if (size > 1024 * 1024) process.exit(1)
          tree-attachments:
            build: { content-type: application/gzip, include-match: build.tgz }
          trial-attachments:
            buildlog: { content-type: application/json, include-match: buildlog.json }

        model:
          name: 'Model/Unit Tests'
          scripts:
            model-tests:
              name: 'Model Tests'
              body: 'npm -s run model-tests > spec/log.txt'
            format-tap:
              body: 'cat spec/log.txt | npm run -s tap-spec -- --color | npm run -s coffee spec/_format-summary.coffee > spec/log.html'
              start-when: [script: model-tests]
          trial-attachments:
            logs_txt: { content-type: text/plain, include-match: spec/log*.txt }
            logs_html: { content-type: text/html, include-match: spec/log*.html }
