jobs:
  Integration-Tests:
    run-on:
    - type: branch
      include-match: ^.*$

    context:

      script-defaults:
        environment-variables_process-templates: true
        environment-variables:
          DISPLAY: ":{{XVNC_PORT}}"
        timeout: 120

      task-defaults:
        _cider-ci_include:
          - cider-ci/defaults/misc.yml
          - cider-ci/defaults/attachments.yml
          - cider-ci/defaults/traits.yml
          - cider-ci/defaults/ports.yml
          - cider-ci/defaults/scripts.yml

      tasks:
        integration:
          name: 'Integration Tests'
          scripts:
            test:
              body: |
                #!/usr/bin/env bash
                npm run -s integration-tests
              start-when:
              - script: api-is-running
              - script: run-selenium
                states: [executing]

  Tests:
    name: All Tests
    descriptions: 'All Tests that need to pass before merging.'
    depends-on:
    - type: job
      job: Integration-Tests
      states: [passed]
    run-on:
    - type: branch
      include-match: ^.+$
    context:
      tasks:
        all:
          scripts:
            body: true
