jobs:
  Integration-Tests:
    run-on:
    - type: branch
      include-match: ^.*$

    context:

      script-defaults:
        environment-variables_process-templates: true
        environment-variables:
          DISPLAY: ":{{XVNC_PORT}}"
        timeout: 120

      task-defaults:
        _cider-ci_include:
          - cider-ci/shared/misc.yml
          - cider-ci/shared/attachments.yml
          - cider-ci/shared/traits.yml
          - cider-ci/shared/ports.yml
          - cider-ci/shared/scripts.yml
        scripts:
          _cider-ci_include:
            - 'cider-ci/shared/scripts/npm-install.yml'
            - 'cider-ci/shared/scripts/manage-database.yml'
            - 'cider-ci/shared/scripts/manage-xvnc.yml'
            - 'cider-ci/shared/scripts/run-services.yml'
            - 'cider-ci/shared/scripts/shutdown-and-cleanup.yml'

      tasks:
        integration:
          name: 'Integration Tests'
          scripts:
            test:
              body: |
                #!/usr/bin/env bash
                npm run -s integration-tests
              start-when:
              - script: build
              - script: api-is-running
              - script: run-selenium
                states: [executing]

  Tests:
    name: All Tests
    descriptions: 'All Tests that need to pass before merging.'
    depends-on:
    - type: job
      job: Integration-Tests
      states: [passed]
    run-on:
    - type: branch
      include-match: ^.+$
    context:
      tasks:
        all:
          scripts:
            body: true
