jobs:
  Integration-Tests:
    run-on:
    - type: branch
      include-match: ^.*$

    context:

      script-defaults:
        environment-variables_process-templates: true
        environment-variables:
          DISPLAY: ":{{XVNC_PORT}}"
        timeout: 120

      task-defaults:
        _cider-ci_include:
          - cider-ci/defaults/misc.yml
          - cider-ci/defaults/attachments.yml
          - cider-ci/defaults/traits.yml
          - cider-ci/defaults/ports.yml
          - cider-ci/defaults/scripts.yml

      tasks:
        integration:
          name: 'Integration Tests'
          scripts:
            'test':
              name: 'Browser Integration Tests'
              body: 'npm run -s integration-tests'
              start-when:
                - script: start-vnc
                - script: api-is-running
                - script: run-selenium
                  states: [executing]

        # TODO:
        # unit:
        #   name: 'Unit Tests'
        #   scripts:
        #     'tap-test':
        #       name: 'Model Tests'
        #       body: 'npm run -s model-tests | tee spec/log.txt'
        #       start-when:
        #       - script: 'npm-install'
        #
